package cmd

import (
	"fmt"
	"io"
	"os"
	"strings"
	"text/template"
	"unicode"
)

// readModuleName reads the Go module name from go.mod in the current directory.
func readModuleName() (string, error) {
	f, err := os.Open("go.mod")
	if err != nil {
		return "", fmt.Errorf("打开 go.mod 失败: %w", err)
	}
	defer f.Close()

	all, err := io.ReadAll(f)
	if err != nil {
		return "", fmt.Errorf("读取 go.mod 失败: %w", err)
	}

	for _, line := range strings.Split(string(all), "\n") {
		line = strings.TrimSpace(line)
		parts := strings.Fields(line)
		if len(parts) == 2 && parts[0] == "module" {
			return parts[1], nil
		}
	}
	return "", fmt.Errorf("go.mod 中未找到 module 声明")
}

// generateFile renders tmplStr with data and writes to path.
// If protect is true, an existing file whose first line does NOT contain the
// generated marker is left untouched (schema files always pass protect=true
// and are never overwritten).
func generateFile(path, tmplStr string, data any, protect bool) error {
	if err := os.MkdirAll(dirOf(path), 0755); err != nil {
		return fmt.Errorf("创建目录失败 %s: %w", dirOf(path), err)
	}

	if exists, err := pathExists(path); err != nil {
		return err
	} else if exists {
		if protect {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("读取文件失败 %s: %w", path, err)
		}
		if !strings.Contains(string(content), "Code generated by newapi. DO NOT EDIT.") {
			return nil
		}
	}

	tmpl, err := template.New("").Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("解析模板失败: %w", err)
	}

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
	if err != nil {
		return fmt.Errorf("创建文件失败 %s: %w", path, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("渲染模板失败: %w", err)
	}
	return nil
}

// pathExists returns (true, nil) if path exists, (false, nil) if it does not,
// or (false, err) for any other error (e.g. permission denied).
func pathExists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, fmt.Errorf("访问路径失败 %s: %w", path, err)
}

// CamelCaseToUnderscore converts PascalCase/camelCase to snake_case.
func CamelCaseToUnderscore(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i == 0 {
			b.WriteRune(unicode.ToLower(r))
		} else {
			if unicode.IsUpper(r) {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
		}
	}
	return b.String()
}

// GetPathVar extracts path parameter names from a path like /user/{id}/posts/{postId}.
func GetPathVar(path string) []string {
	var vars []string
	var cur strings.Builder
	inParam := false
	for _, r := range path {
		switch {
		case r == '{':
			inParam = true
		case r == '}' && inParam:
			inParam = false
			vars = append(vars, cur.String())
			cur.Reset()
		case inParam:
			cur.WriteRune(r)
		}
	}
	return vars
}

// dirOf returns the directory component of a file path.
func dirOf(path string) string {
	idx := strings.LastIndexAny(path, "/\\")
	if idx < 0 {
		return "."
	}
	return path[:idx]
}

// fatal prints msg to stderr and exits with code 1.
func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "错误: "+format+"\n", args...)
	os.Exit(1)
}
