package generator

import (
	_ "embed"
	"fmt"
	"os"
	"strings"
	"text/template"
)

//go:embed templates/endpoint.tmpl
var endpointTmpl string

//go:embed templates/service.tmpl
var serviceTmpl string

//go:embed templates/schema.tmpl
var schemaTmpl string

// ApiTemp holds the data used to render all three code templates for one API.
type ApiTemp struct {
	ProjectName string
	ApiName     string
	Path        string
	RouterPath  string
	Desc        string
	Tag         string
	Method      string
	GenCommand  string
	PathVar     []string
}

// GenEndpoint generates the endpoint file for the given API.
func GenEndpoint(a ApiTemp) error {
	path := fmt.Sprintf("endpoints/%s_ep.go", CamelCaseToUnderscore(a.ApiName))
	return generateFile(path, endpointTmpl, a, false)
}

// GenService generates the service file for the given API.
func GenService(a ApiTemp) error {
	path := fmt.Sprintf("services/%s_srv.go", CamelCaseToUnderscore(a.ApiName))
	return generateFile(path, serviceTmpl, a, false)
}

// GenSchema generates the schema file for the given API.
// Schema files are never overwritten once created.
func GenSchema(a ApiTemp) error {
	path := fmt.Sprintf("schemas/%s_schema.go", CamelCaseToUnderscore(a.ApiName))
	return generateFile(path, schemaTmpl, a, true)
}

// generateFile renders tmplStr with data and writes to path.
// If protect is true, an existing file is never overwritten (used for schema).
// Otherwise, an existing file is only overwritten if it contains the generated marker.
func generateFile(path, tmplStr string, data any, protect bool) error {
	if err := os.MkdirAll(dirOf(path), 0755); err != nil {
		return fmt.Errorf("创建目录失败 %s: %w", dirOf(path), err)
	}

	if exists, err := pathExists(path); err != nil {
		return err
	} else if exists {
		if protect {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("读取文件失败 %s: %w", path, err)
		}
		if !strings.Contains(string(content), "Code generated by newapi. DO NOT EDIT.") {
			return nil
		}
	}

	tmpl, err := template.New("").Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("解析模板失败: %w", err)
	}

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
	if err != nil {
		return fmt.Errorf("创建文件失败 %s: %w", path, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("渲染模板失败: %w", err)
	}
	return nil
}
